export const CLIENT_ERROR_TYPE_BAD_REQUEST = 'bad-request'
export const CLIENT_ERROR_TYPE_CONFLICT = 'conflict'
export const CLIENT_ERROR_TYPE_CONTENT_TOO_LARGE = 'content-too-large'
export const CLIENT_ERROR_TYPE_EXPECTATION_FAILED = 'expectation-failed'
export const CLIENT_ERROR_TYPE_FAILED_DEPENDENCY = 'failed-dependency'
export const CLIENT_ERROR_TYPE_FORBIDDEN = 'forbidden'
export const CLIENT_ERROR_TYPE_GONE = 'gone'
export const CLIENT_ERROR_TYPE_I_M_A_TEAPOT = 'i-m-a-teapot'
export const CLIENT_ERROR_TYPE_LENGTH_REQUIRED = 'length-required'
export const CLIENT_ERROR_TYPE_LOCKED = 'locked'
export const CLIENT_ERROR_TYPE_METHOD_NOT_ALLOWED = 'method-not-allowed'
export const CLIENT_ERROR_TYPE_MISDIRECTED_REQUEST = 'misdirected-request'
export const CLIENT_ERROR_TYPE_NOT_ACCEPTABLE = 'not-acceptable'
export const CLIENT_ERROR_TYPE_NOT_FOUND = 'not-found'
export const CLIENT_ERROR_TYPE_PAYMENT_REQUIRED = 'payment-required'
export const CLIENT_ERROR_TYPE_PRECONDITION_FAILED = 'precondition-failed'
export const CLIENT_ERROR_TYPE_PRECONDITION_REQUIRED = 'precondition-required'
export const CLIENT_ERROR_TYPE_PROXY_AUTHENTICATION_REQUIRED = 'proxy-authentication-required'
export const CLIENT_ERROR_TYPE_RANGE_NOT_SATISFIABLE = 'range-not-satisfiable'
export const CLIENT_ERROR_TYPE_REQUEST_HEADER_FIELDS_TOO_LARGE = 'request-header-fields-too-large'
export const CLIENT_ERROR_TYPE_REQUEST_TIMEOUT = 'request-timeout'
export const CLIENT_ERROR_TYPE_TOO_EARLY = 'too-early'
export const CLIENT_ERROR_TYPE_TOO_MANY_REQUESTS = 'too-many-requests'
export const CLIENT_ERROR_TYPE_UNAUTHORIZED = 'unauthorized'
export const CLIENT_ERROR_TYPE_UNAVAILABLE_FOR_LEGAL_REASONS = 'unavailable-for-legal-reasons'
export const CLIENT_ERROR_TYPE_UNPROCESSABLE_CONTENT = 'unprocessable-content'
export const CLIENT_ERROR_TYPE_UNSUPPORTED_MEDIA_TYPE = 'unsupported-media-type'
export const CLIENT_ERROR_TYPE_UPGRADE_REQUIRED = 'upgrade-required'
export const CLIENT_ERROR_TYPE_URI_TOO_LONG = 'uri-too-long'

export const CLIENT_ERROR_TYPES = {
	BAD_REQUEST: CLIENT_ERROR_TYPE_BAD_REQUEST,
	CONFLICT: CLIENT_ERROR_TYPE_CONFLICT,
	CONTENT_TOO_LARGE: CLIENT_ERROR_TYPE_CONTENT_TOO_LARGE,
	EXPECTATION_FAILED: CLIENT_ERROR_TYPE_EXPECTATION_FAILED,
	FAILED_DEPENDENCY: CLIENT_ERROR_TYPE_FAILED_DEPENDENCY,
	FORBIDDEN: CLIENT_ERROR_TYPE_FORBIDDEN,
	GONE: CLIENT_ERROR_TYPE_GONE,
	I_M_A_TEAPOT: CLIENT_ERROR_TYPE_I_M_A_TEAPOT,
	LENGTH_REQUIRED: CLIENT_ERROR_TYPE_LENGTH_REQUIRED,
	LOCKED: CLIENT_ERROR_TYPE_LOCKED,
	METHOD_NOT_ALLOWED: CLIENT_ERROR_TYPE_METHOD_NOT_ALLOWED,
	MISDIRECTED_REQUEST: CLIENT_ERROR_TYPE_MISDIRECTED_REQUEST,
	NOT_ACCEPTABLE: CLIENT_ERROR_TYPE_NOT_ACCEPTABLE,
	NOT_FOUND: CLIENT_ERROR_TYPE_NOT_FOUND,
	PAYMENT_REQUIRED: CLIENT_ERROR_TYPE_PAYMENT_REQUIRED,
	PRECONDITION_FAILED: CLIENT_ERROR_TYPE_PRECONDITION_FAILED,
	PRECONDITION_REQUIRED: CLIENT_ERROR_TYPE_PRECONDITION_REQUIRED,
	PROXY_AUTHENTICATION_REQUIRED: CLIENT_ERROR_TYPE_PROXY_AUTHENTICATION_REQUIRED,
	RANGE_NOT_SATISFIABLE: CLIENT_ERROR_TYPE_RANGE_NOT_SATISFIABLE,
	REQUEST_HEADER_FIELDS_TOO_LARGE: CLIENT_ERROR_TYPE_REQUEST_HEADER_FIELDS_TOO_LARGE,
	REQUEST_TIMEOUT: CLIENT_ERROR_TYPE_REQUEST_TIMEOUT,
	TOO_EARLY: CLIENT_ERROR_TYPE_TOO_EARLY,
	TOO_MANY_REQUESTS: CLIENT_ERROR_TYPE_TOO_MANY_REQUESTS,
	UNAUTHORIZED: CLIENT_ERROR_TYPE_UNAUTHORIZED,
	UNAVAILABLE_FOR_LEGAL_REASONS: CLIENT_ERROR_TYPE_UNAVAILABLE_FOR_LEGAL_REASONS,
	UNPROCESSABLE_CONTENT: CLIENT_ERROR_TYPE_UNPROCESSABLE_CONTENT,
	UNSUPPORTED_MEDIA_TYPE: CLIENT_ERROR_TYPE_UNSUPPORTED_MEDIA_TYPE,
	UPGRADE_REQUIRED: CLIENT_ERROR_TYPE_UPGRADE_REQUIRED,
	URI_TOO_LONG: CLIENT_ERROR_TYPE_URI_TOO_LONG,
} as const

export const CLIENT_ERROR_CODE_BAD_REQUEST = 400
export const CLIENT_ERROR_CODE_CONFLICT = 409
export const CLIENT_ERROR_CODE_CONTENT_TOO_LARGE = 413
export const CLIENT_ERROR_CODE_EXPECTATION_FAILED = 417
export const CLIENT_ERROR_CODE_FAILED_DEPENDENCY = 424
export const CLIENT_ERROR_CODE_FORBIDDEN = 403
export const CLIENT_ERROR_CODE_GONE = 410
export const CLIENT_ERROR_CODE_I_M_A_TEAPOT = 418
export const CLIENT_ERROR_CODE_LENGTH_REQUIRED = 411
export const CLIENT_ERROR_CODE_LOCKED = 423
export const CLIENT_ERROR_CODE_METHOD_NOT_ALLOWED = 405
export const CLIENT_ERROR_CODE_MISDIRECTED_REQUEST = 421
export const CLIENT_ERROR_CODE_NOT_ACCEPTABLE = 406
export const CLIENT_ERROR_CODE_NOT_FOUND = 404
export const CLIENT_ERROR_CODE_PAYMENT_REQUIRED = 402
export const CLIENT_ERROR_CODE_PRECONDITION_FAILED = 412
export const CLIENT_ERROR_CODE_PRECONDITION_REQUIRED = 428
export const CLIENT_ERROR_CODE_PROXY_AUTHENTICATION_REQUIRED = 407
export const CLIENT_ERROR_CODE_RANGE_NOT_SATISFIABLE = 416
export const CLIENT_ERROR_CODE_REQUEST_HEADER_FIELDS_TOO_LARGE = 431
export const CLIENT_ERROR_CODE_REQUEST_TIMEOUT = 408
export const CLIENT_ERROR_CODE_TOO_EARLY = 425
export const CLIENT_ERROR_CODE_TOO_MANY_REQUESTS = 429
export const CLIENT_ERROR_CODE_UNAUTHORIZED = 401
export const CLIENT_ERROR_CODE_UNAVAILABLE_FOR_LEGAL_REASONS = 451
export const CLIENT_ERROR_CODE_UNPROCESSABLE_CONTENT = 422
export const CLIENT_ERROR_CODE_UNSUPPORTED_MEDIA_TYPE = 415
export const CLIENT_ERROR_CODE_UPGRADE_REQUIRED = 426
export const CLIENT_ERROR_CODE_URI_TOO_LONG = 414

export const CLIENT_ERROR_CODES = {
	BAD_REQUEST: CLIENT_ERROR_CODE_BAD_REQUEST,
	CONFLICT: CLIENT_ERROR_CODE_CONFLICT,
	CONTENT_TOO_LARGE: CLIENT_ERROR_CODE_CONTENT_TOO_LARGE,
	EXPECTATION_FAILED: CLIENT_ERROR_CODE_EXPECTATION_FAILED,
	FAILED_DEPENDENCY: CLIENT_ERROR_CODE_FAILED_DEPENDENCY,
	FORBIDDEN: CLIENT_ERROR_CODE_FORBIDDEN,
	GONE: CLIENT_ERROR_CODE_GONE,
	I_M_A_TEAPOT: CLIENT_ERROR_CODE_I_M_A_TEAPOT,
	LENGTH_REQUIRED: CLIENT_ERROR_CODE_LENGTH_REQUIRED,
	LOCKED: CLIENT_ERROR_CODE_LOCKED,
	METHOD_NOT_ALLOWED: CLIENT_ERROR_CODE_METHOD_NOT_ALLOWED,
	MISDIRECTED_REQUEST: CLIENT_ERROR_CODE_MISDIRECTED_REQUEST,
	NOT_ACCEPTABLE: CLIENT_ERROR_CODE_NOT_ACCEPTABLE,
	NOT_FOUND: CLIENT_ERROR_CODE_NOT_FOUND,
	PAYMENT_REQUIRED: CLIENT_ERROR_CODE_PAYMENT_REQUIRED,
	PRECONDITION_FAILED: CLIENT_ERROR_CODE_PRECONDITION_FAILED,
	PRECONDITION_REQUIRED: CLIENT_ERROR_CODE_PRECONDITION_REQUIRED,
	PROXY_AUTHENTICATION_REQUIRED: CLIENT_ERROR_CODE_PROXY_AUTHENTICATION_REQUIRED,
	RANGE_NOT_SATISFIABLE: CLIENT_ERROR_CODE_RANGE_NOT_SATISFIABLE,
	REQUEST_HEADER_FIELDS_TOO_LARGE: CLIENT_ERROR_CODE_REQUEST_HEADER_FIELDS_TOO_LARGE,
	REQUEST_TIMEOUT: CLIENT_ERROR_CODE_REQUEST_TIMEOUT,
	TOO_EARLY: CLIENT_ERROR_CODE_TOO_EARLY,
	TOO_MANY_REQUESTS: CLIENT_ERROR_CODE_TOO_MANY_REQUESTS,
	UNAUTHORIZED: CLIENT_ERROR_CODE_UNAUTHORIZED,
	UNAVAILABLE_FOR_LEGAL_REASONS: CLIENT_ERROR_CODE_UNAVAILABLE_FOR_LEGAL_REASONS,
	UNPROCESSABLE_CONTENT: CLIENT_ERROR_CODE_UNPROCESSABLE_CONTENT,
	UNSUPPORTED_MEDIA_TYPE: CLIENT_ERROR_CODE_UNSUPPORTED_MEDIA_TYPE,
	UPGRADE_REQUIRED: CLIENT_ERROR_CODE_UPGRADE_REQUIRED,
	URI_TOO_LONG: CLIENT_ERROR_CODE_URI_TOO_LONG,
} as const


export const CLIENT_CODES = [
	CLIENT_ERROR_CODE_BAD_REQUEST,
	CLIENT_ERROR_CODE_CONFLICT,
	CLIENT_ERROR_CODE_CONTENT_TOO_LARGE,
	CLIENT_ERROR_CODE_EXPECTATION_FAILED,
	CLIENT_ERROR_CODE_FAILED_DEPENDENCY,
	CLIENT_ERROR_CODE_FORBIDDEN,
	CLIENT_ERROR_CODE_GONE,
	CLIENT_ERROR_CODE_I_M_A_TEAPOT,
	CLIENT_ERROR_CODE_LENGTH_REQUIRED,
	CLIENT_ERROR_CODE_LOCKED,
	CLIENT_ERROR_CODE_METHOD_NOT_ALLOWED,
	CLIENT_ERROR_CODE_MISDIRECTED_REQUEST,
	CLIENT_ERROR_CODE_NOT_ACCEPTABLE,
	CLIENT_ERROR_CODE_NOT_FOUND,
	CLIENT_ERROR_CODE_PAYMENT_REQUIRED,
	CLIENT_ERROR_CODE_PRECONDITION_FAILED,
	CLIENT_ERROR_CODE_PRECONDITION_REQUIRED,
	CLIENT_ERROR_CODE_PROXY_AUTHENTICATION_REQUIRED,
	CLIENT_ERROR_CODE_RANGE_NOT_SATISFIABLE,
	CLIENT_ERROR_CODE_REQUEST_HEADER_FIELDS_TOO_LARGE,
	CLIENT_ERROR_CODE_REQUEST_TIMEOUT,
	CLIENT_ERROR_CODE_TOO_EARLY,
	CLIENT_ERROR_CODE_TOO_MANY_REQUESTS,
	CLIENT_ERROR_CODE_UNAUTHORIZED,
	CLIENT_ERROR_CODE_UNAVAILABLE_FOR_LEGAL_REASONS,
	CLIENT_ERROR_CODE_UNPROCESSABLE_CONTENT,
	CLIENT_ERROR_CODE_UNSUPPORTED_MEDIA_TYPE,
	CLIENT_ERROR_CODE_UPGRADE_REQUIRED,
	CLIENT_ERROR_CODE_URI_TOO_LONG,,
] as const

export type ClientCode = typeof CLIENT_CODES[number]
export type ClientErrorCode = typeof CLIENT_ERROR_CODES[keyof typeof CLIENT_ERROR_CODES]
export type ClientErrorType = typeof CLIENT_ERROR_TYPES[keyof typeof CLIENT_ERROR_TYPES]